# Generated by Django 2.2 on 2019-09-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190911_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default1.png', upload_to='profile_pics'),
        ),
    ]
